---
- hosts: all
  connection: ssh
  
  tasks:
    - name: install web server
      yum: name=httpd state=present

    - name: start webserver
      service: name=httpd state=started

    - name: install git
      yum: name=git state=present

    - name: Delete existing directory
      file:
        path: /var/www/
        state: absent


    - name: get the source code from github
      git:
        repo: "https://github.com/devops0014/staticsite-docker.git"
        dest: /var/www/
        update: yes
        version: master
